# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TyG8xInJNQwaNsuYgriD28zy_fsL-V1
"""

import streamlit as st
import pandas as pd
import numpy as np
import shap
import networkx as nx
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score
from xgboost import XGBClassifier

st.set_page_config(page_title="CardioGraph AI", layout="wide")

st.title("❤️ CardioGraph AI")
st.subheader("Explainable Cardiovascular Risk Prediction System")

# --------------------------
# LOAD DATA
# --------------------------

@st.cache_data
def load_data():

    df = pd.read_csv("cardio_train.csv", sep=";")

    df["BMI"] = df["weight"] / ((df["height"]/100)**2)

    return df


df = load_data()

features = [
    "age","gender","BMI","ap_hi","ap_lo",
    "cholesterol","gluc","smoke","alco","active"
]

X = df[features]
y = df["cardio"]

# --------------------------
# TRAIN MODEL
# --------------------------

@st.cache_resource
def train_model():

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(X)

    X_train,X_test,y_train,y_test = train_test_split(
        X_scaled,y,test_size=0.2,random_state=42
    )

    model = XGBClassifier(eval_metric="logloss")

    model.fit(X_train,y_train)

    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:,1]

    acc = accuracy_score(y_test,preds)
    auc = roc_auc_score(y_test,probs)

    explainer = shap.TreeExplainer(model)

    return model, scaler, acc, auc, explainer


model, scaler, acc, auc, explainer = train_model()

st.write("Model Accuracy:", round(acc,3))
st.write("Model ROC-AUC:", round(auc,3))

# --------------------------
# USER INPUT
# --------------------------

st.sidebar.header("Patient Profile")

age = st.sidebar.slider("Age",20,80,50)

gender_option = st.sidebar.selectbox("Gender",["Female","Male"])
gender = 1 if gender_option=="Female" else 2

height = st.sidebar.slider("Height (cm)",140,200,170)
weight = st.sidebar.slider("Weight (kg)",40,150,70)

ap_hi = st.sidebar.slider("Systolic Blood Pressure",90,200,120)
ap_lo = st.sidebar.slider("Diastolic Blood Pressure",60,140,80)

chol_map = {"Normal":1,"Above Normal":2,"Well Above Normal":3}
chol_label = st.sidebar.selectbox("Cholesterol Level",list(chol_map.keys()))
cholesterol = chol_map[chol_label]

gluc_map = {"Normal":1,"Above Normal":2,"Well Above Normal":3}
gluc_label = st.sidebar.selectbox("Glucose Level",list(gluc_map.keys()))
gluc = gluc_map[gluc_label]

smoke_option = st.sidebar.selectbox("Smoking",["No","Yes"])
smoke = 1 if smoke_option=="Yes" else 0

alco_option = st.sidebar.selectbox("Alcohol Consumption",["No","Yes"])
alco = 1 if alco_option=="Yes" else 0

activity_option = st.sidebar.selectbox("Physical Activity",["No","Yes"])
active = 1 if activity_option=="Yes" else 0

BMI = weight / ((height/100)**2)

user = np.array([[age,gender,BMI,ap_hi,ap_lo,
                  cholesterol,gluc,smoke,alco,active]])

user_scaled = scaler.transform(user)

# --------------------------
# PREDICTION
# --------------------------

if st.button("Predict Cardiovascular Risk"):

    prob = model.predict_proba(user_scaled)[0][1]

    st.header("Risk Prediction")

    st.metric("Estimated Risk", f"{prob*100:.2f}%")

    if prob < 0.3:
        st.success("Low Cardiovascular Risk")
    elif prob < 0.6:
        st.warning("Moderate Cardiovascular Risk")
    else:
        st.error("High Cardiovascular Risk")

# --------------------------
# SHAP EXPLANATION
# --------------------------

    st.subheader("AI Explanation (What influenced the prediction?)")

    shap_values = explainer.shap_values(user_scaled)

    shap_contrib = shap_values[0]

    fig, ax = plt.subplots()

    ax.barh(features, shap_contrib)

    ax.set_xlabel("Impact on Prediction")

    st.pyplot(fig)

# --------------------------
# COUNTERFACTUAL SUGGESTIONS
# --------------------------

    st.subheader("Suggested Lifestyle Improvements")

    impact = dict(zip(features, shap_contrib))

    sorted_features = sorted(impact.items(), key=lambda x: x[1], reverse=True)

    suggestions = []
    sim = user.copy()

    for feature, value in sorted_features:

        if feature == "smoke" and smoke == 1:
            suggestions.append("Stop smoking")
            sim[0][7] = 0

        elif feature == "BMI" and BMI > 25:
            suggestions.append("Reduce BMI to around 24")
            sim[0][2] = 24

        elif feature == "active" and active == 0:
            suggestions.append("Increase physical activity")
            sim[0][9] = 1

        elif feature == "cholesterol" and cholesterol > 1:
            suggestions.append("Lower cholesterol through diet")

        if len(suggestions) == 3:
            break

    for s in suggestions:
        st.write("•", s)

    sim_scaled = scaler.transform(sim)

    new_prob = model.predict_proba(sim_scaled)[0][1]

    st.write("New Predicted Risk:", round(new_prob*100,2), "%")

# --------------------------
# RISK NETWORK GRAPH
# --------------------------

    st.subheader("Risk Factor Network")

    G = nx.DiGraph()

    edges = [
        ("Smoking","Heart Disease"),
        ("Cholesterol","Heart Disease"),
        ("Blood Pressure","Heart Disease"),
        ("Glucose","Heart Disease"),
        ("BMI","Blood Pressure"),
        ("Physical Activity","BMI")
    ]

    G.add_edges_from(edges)

    node_colors = []

    for node in G.nodes():

        if node=="Smoking" and smoke==1:
            node_colors.append("red")

        elif node=="BMI" and BMI>30:
            node_colors.append("orange")

        elif node=="Physical Activity" and active==1:
            node_colors.append("green")

        else:
            node_colors.append("skyblue")

    fig2 = plt.figure(figsize=(6,6))

    pos = nx.spring_layout(G, seed=42)

    nx.draw(
        G,
        pos,
        with_labels=True,
        node_size=2500,
        node_color=node_colors,
        arrows=True
    )

    st.pyplot(fig2)

# --------------------------
# DATASET INSIGHT
# --------------------------

st.subheader("Dataset Overview")

st.write("Total Patients:", len(df))
st.write("Disease Rate:", round(df["cardio"].mean()*100,2), "%")