# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TyG8xInJNQwaNsuYgriD28zy_fsL-V1
"""
import streamlit as st
import pandas as pd
import numpy as np
import shap
import plotly.express as px
import networkx as nx

from pyvis.network import Network
from streamlit.components.v1 import html

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score
from xgboost import XGBClassifier

st.set_page_config(page_title="CardioGraph AI", layout="wide")

st.title("CardioGraph AI")
st.subheader("Explainable Cardiovascular Risk Prediction System")

# --------------------------
# LOAD DATA
# --------------------------

@st.cache_data
def load_data():
    df = pd.read_csv("cardio_train.csv", sep=";")
    df["BMI"] = df["weight"] / ((df["height"]/100)**2)
    return df

df = load_data()

features = [
    "age","gender","BMI","ap_hi","ap_lo",
    "cholesterol","gluc","smoke","alco","active"
]

X = df[features]
y = df["cardio"]

# --------------------------
# TRAIN MODEL
# --------------------------

@st.cache_resource
def train_model():

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled,
        y,
        test_size=0.2,
        stratify=y,
        random_state=42
    )

    model = XGBClassifier(
        eval_metric="logloss",
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05
    )

    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:,1]

    acc = accuracy_score(y_test, preds)
    auc = roc_auc_score(y_test, probs)

    explainer = shap.TreeExplainer(model)

    return model, scaler, acc, auc, explainer

model, scaler, acc, auc, explainer = train_model()

st.write("Model Accuracy:", round(acc,3))
st.write("Model ROC-AUC:", round(auc,3))

# --------------------------
# USER INPUT
# --------------------------

st.sidebar.header("Patient Health Profile")

age = st.sidebar.slider("Age",20,80,50)

gender_option = st.sidebar.selectbox("Gender",["Female","Male"])
gender = 1 if gender_option=="Female" else 2

height = st.sidebar.slider("Height (cm)",140,200,170)
weight = st.sidebar.slider("Weight (kg)",40,150,70)

ap_hi = st.sidebar.slider("Systolic Blood Pressure",90,200,120)
ap_lo = st.sidebar.slider("Diastolic Blood Pressure",60,140,80)

chol_map = {"Normal":1,"Above Normal":2,"Well Above Normal":3}
cholesterol = chol_map[
    st.sidebar.selectbox("Cholesterol Level",list(chol_map.keys()))
]

gluc_map = {"Normal":1,"Above Normal":2,"Well Above Normal":3}
gluc = gluc_map[
    st.sidebar.selectbox("Glucose Level",list(gluc_map.keys()))
]

smoke = 1 if st.sidebar.selectbox("Smoking",["No","Yes"])=="Yes" else 0
alco = 1 if st.sidebar.selectbox("Alcohol Consumption",["No","Yes"])=="Yes" else 0
active = 1 if st.sidebar.selectbox("Regular Physical Activity",["No","Yes"])=="Yes" else 0

BMI = weight / ((height/100)**2)

user = np.array([[age,gender,BMI,ap_hi,ap_lo,
                  cholesterol,gluc,smoke,alco,active]])

user_scaled = scaler.transform(user)

# --------------------------
# PREDICTION
# --------------------------

if st.button("Predict Cardiovascular Risk"):

    prob = model.predict_proba(user_scaled)[0][1]

    st.header("Risk Prediction")

    st.metric("Estimated Cardiovascular Risk", f"{prob*100:.2f}%")

    if prob < 0.3:
        st.success("Low Cardiovascular Risk")
    elif prob < 0.6:
        st.warning("Moderate Cardiovascular Risk")
    else:
        st.error("High Cardiovascular Risk")

# --------------------------
# SHAP EXPLANATION (PLOTLY)
# --------------------------

    st.subheader("AI Explanation")

    shap_values = explainer.shap_values(user_scaled)
    shap_contrib = shap_values[0]

    impact_df = pd.DataFrame({
        "Feature": features,
        "Impact": shap_contrib
    })

    fig = px.bar(
        impact_df,
        x="Impact",
        y="Feature",
        orientation="h",
        title="Feature Impact on Prediction",
        color="Impact"
    )

    st.plotly_chart(fig)

# --------------------------
# COUNTERFACTUAL SUGGESTIONS
# --------------------------

    st.subheader("Suggested Lifestyle Improvements")

    impact = dict(zip(features, shap_contrib))
    sorted_features = sorted(impact.items(), key=lambda x: x[1], reverse=True)

    suggestions = []
    sim = user.copy()

    for feature, value in sorted_features:

        if feature=="smoke" and smoke==1:
            suggestions.append("Stop smoking")
            sim[0][7] = 0

        elif feature=="BMI" and BMI>25:
            suggestions.append("Reduce BMI to around 24")
            sim[0][2] = 24

        elif feature=="active" and active==0:
            suggestions.append("Increase physical activity")
            sim[0][9] = 1

        elif feature=="cholesterol" and cholesterol>1:
            suggestions.append("Improve cholesterol through diet")

        elif feature=="alco" and alco==1:
            suggestions.append("Reduce alcohol consumption")

        if len(suggestions)==3:
            break

    for s in suggestions:
        st.write("•",s)

    sim_scaled = scaler.transform(sim)
    new_prob = model.predict_proba(sim_scaled)[0][1]

    st.write("New Predicted Risk:", round(new_prob*100,2), "%")

# --------------------------
# PYVIS NETWORK GRAPH
# --------------------------

    st.subheader("Risk Factor Network")

    G = nx.DiGraph()

    edges = [
        ("Smoking","Blood Pressure"),
        ("Blood Pressure","Heart Disease"),
        ("Cholesterol","Heart Disease"),
        ("Glucose","Heart Disease"),
        ("Alcohol","Heart Disease"),
        ("Physical Activity","BMI"),
        ("BMI","Blood Pressure")
    ]

    G.add_edges_from(edges)

    net = Network(height="500px", width="100%", directed=True)

    for node in G.nodes():

        color="skyblue"

        if node=="Smoking" and smoke==1:
            color="red"

        elif node=="Alcohol" and alco==1:
            color="orange"

        elif node=="Cholesterol" and cholesterol>1:
            color="red"

        elif node=="Glucose" and gluc>1:
            color="orange"

        elif node=="Blood Pressure" and ap_hi>140:
            color="red"

        elif node=="BMI" and BMI>30:
            color="orange"

        elif node=="Physical Activity" and active==1:
            color="green"

        net.add_node(node,label=node,color=color)

    for edge in G.edges():
        net.add_edge(edge[0],edge[1])

    net.save_graph("graph.html")

    HtmlFile=open("graph.html",'r',encoding='utf-8')
    source_code=HtmlFile.read()

    html(source_code,height=500)

# --------------------------
# DATASET INSIGHTS
# --------------------------

st.subheader("Dataset Overview")

st.write("Total Patients:", len(df))
st.write("Cardiovascular Disease Rate:", round(df["cardio"].mean()*100,2), "%")
